In [1]:
import pandas as pd

In [6]:
df = pd.read_csv(('./input/battles.csv'), encoding = 'ISO-8859-1')
df.columns

Index(['name', 'year', 'battle_number', 'attacker_king', 'defender_king',
       'attacker_1', 'attacker_2', 'attacker_3', 'attacker_4', 'defender_1',
       'defender_2', 'defender_3', 'defender_4', 'attacker_outcome',
       'battle_type', 'major_death', 'major_capture', 'attacker_size',
       'defender_size', 'attacker_commander', 'defender_commander', 'summer',
       'location', 'region', 'note'],
      dtype='object')

In [7]:
df.head()

,name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,...,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note
0,Battle of the Golden Tooth,298,1,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,1.0,0.0,15000.0,4000.0,Jaime Lannister,"Clement Piper, Vance",1.0,Golden Tooth,The Westerlands,NaN
1,Battle at the Mummer's Ford,298,2,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Baratheon,...,1.0,0.0,NaN,120.0,Gregor Clegane,Beric Dondarrion,1.0,Mummer's Ford,The Riverlands,NaN
2,Battle of Riverrun,298,3,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,0.0,1.0,15000.0,10000.0,"Jaime Lannister, Andros Brax","Edmure Tully, Tytos Blackwood",1.0,Riverrun,The Riverlands,NaN
3,Battle of the Green Fork,298,4,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,1.0,1.0,18000.0,20000.0,"Roose Bolton, Wylis Manderly, Medger Cerwyn, H...","Tywin Lannister, Gregor Clegane, Kevan Lannist...",1.0,Green Fork,The Riverlands,NaN
4,Battle of the Whispering Wood,298,5,Robb Stark,Joffrey/Tommen Baratheon,Stark,Tully,NaN,NaN,Lannister,...,1.0,1.0,1875.0,6000.0,"Robb Stark, Brynden Tully",Jaime Lannister,1.0,Whispering Wood,The Riverlands,NaN

In [10]:
df2 = pd.read_csv(('./input/character-deaths.csv'), encoding = 'ISO-8859-1')
df2

,Name,Allegiances,Death Year,Book of Death,Death Chapter,Book Intro Chapter,Gender,Nobility,GoT,CoK,SoS,FfC,DwD
0,Addam Marbrand,Lannister,NaN,NaN,NaN,56.0,1,1,1,1,1,1,0
1,Aegon Frey (Jinglebell),None,299.0,3.0,51.0,49.0,1,1,0,0,1,0,0
2,Aegon Targaryen,House Targaryen,NaN,NaN,NaN,5.0,1,1,0,0,0,0,1
3,Adrack Humble,House Greyjoy,300.0,5.0,20.0,20.0,1,1,0,0,0,0,1
4,Aemon Costayne,Lannister,NaN,NaN,NaN,NaN,1,1,0,0,1,0,0
5,Aemon Estermont,Baratheon,NaN,NaN,NaN,NaN,1,1,0,1,1,0,0
6,Aemon Targaryen (son of Maekar I),Night's Watch,300.0,4.0,35.0,21.0,1,1,1,0,1,1,0
7,Aenys Frey,None,300.0,5.0,NaN,59.0,0,1,1,1,1,0,1
8,Aeron Greyjoy,House Greyjoy,NaN,NaN,NaN,11.0,1,1,0,1,0,1,0
9,Aethan,Night's Watch,NaN,NaN,NaN,0.0,1,0,0,0,1,0,0
10,Aggar,House Greyjoy,299.0,2.0,56.0,50.0,1,0,0,1,0,0,0
11,Aggo,House Targaryen,NaN,NaN,NaN,54.0,1,0,1,1,1,0,1
12,Alan of Rosby,Night's Watch,300.0,5.0,4.0,18.0,1,1,0,1,1,0,1
13,Alayaya,None,NaN,NaN,NaN,15.0,0,0,0,1,0,0,0
14,Albar Royce,Arryn,NaN,NaN,NaN,38.0,1,1,1,0,0,1,0
15,Albett,Night's Watch,NaN,NaN,NaN,26.0,1,0,1,0,0,0,0
16,Alebelly,House Stark,299.0,2.0,46.0,4.0,1,0,0,1,0,0,0
17,Alerie Hightower,House Tyrell,NaN,NaN,NaN,6.0,0,1,0,0,1,1,0
18,Alesander Staedmon,Baratheon,NaN,NaN,NaN,65.0,1,1,0,1,0,0,0
19,Alester Florent,Baratheon,300.0,4.0,NaN,36.0,1,1,0,1,1,0,0
20,Alia of Braavos,None,NaN,NaN,NaN,28.0,0,0,1,0,0,0,0
21,Alla Tyrell,House Tyrell,NaN,NaN,NaN,6.0,0,1,0,0,1,1,0
22,Allard Seaworth,Baratheon,299.0,2.0,10.0,10.0,1,1,0,1,0,0,0
23,Alliser Thorne,Night's Watch,NaN,NaN,NaN,19.0,1,0,1,1,1,0,1
24,Alyn,House Stark,298.0,3.0,34.0,12.0,1,0,1,0,0,0,0
25,Alyn Ambrose,Tyrell,NaN,NaN,NaN,59.0,1,1,0,1,0,1,0
26,Alyn Estermont,Baratheon,NaN,NaN,NaN,NaN,1,1,0,1,1,0,0
27,Alyn Stackspear,Lannister,NaN,NaN,NaN,16.0,1,1,0,0,0,1,0
28,Alys Karstark,Stark,NaN,NaN,NaN,44.0,0,1,0,0,0,0,1
29,Alysane Mormont,Stark,NaN,NaN,NaN,35.0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,Willit,Lannister,NaN,NaN,NaN,65.0,1,0,0,1,0,0,0
888,Willow Witch-eye,Wildling,300.0,5.0,69.0,37.0,0,0,0,0,0,0,1
889,Willum,Tully,NaN,NaN,NaN,43.0,1,0,1,0,0,0,0
890,Woth,Night's Watch,299.0,2.0,14.0,14.0,1,0,0,1,0,0,0
891,Wulfe,House Greyjoy,NaN,NaN,NaN,29.0,1,0,0,0,0,1,1
892,Wun Weg Wun Dar Wun,Wildling,NaN,NaN,NaN,35.0,1,0,0,0,0,0,1
893,Wyl (guard),House Stark,298.0,1.0,35.0,35.0,1,0,1,0,0,0,0
894,Wyl the Whittler,None,299.0,3.0,34.0,34.0,1,0,0,0,1,0,0
895,Wylis Manderly,Stark,NaN,NaN,NaN,55.0,1,1,1,1,0,1,0
896,Wylla Manderly,Stark,NaN,NaN,NaN,19.0,0,1,0,0,0,0,1
897,Wyman Manderly,Stark,NaN,NaN,NaN,16.0,1,1,0,1,0,0,1
898,Wynafryd Manderly,Stark,NaN,NaN,NaN,19.0,1,1,0,0,0,0,1
899,Wynton Stout,Night's Watch,NaN,NaN,NaN,41.0,1,0,0,0,1,0,0
900,Xaro Xhoan Daxos,None,NaN,NaN,NaN,12.0,1,1,0,1,0,0,1
901,Xhondo,None,NaN,NaN,NaN,26.0,1,0,0,0,0,1,0
902,Yandry,House Targaryen,NaN,NaN,NaN,8.0,1,0,0,0,0,0,1
903,Yellow Dick,None,300.0,5.0,46.0,12.0,1,0,0,0,0,0,1
904,Ygon Farwynd,Greyjoy,NaN,NaN,NaN,19.0,1,1,0,0,0,1,0
905,Ygritte,Wildling,299.0,3.0,55.0,51.0,0,0,0,1,1,0,0
906,Yohn Farwynd,Greyjoy,NaN,NaN,NaN,19.0,1,1,0,0,0,1,0
907,Yohn Royce,Arryn,NaN,NaN,NaN,29.0,1,1,1,0,0,1,0
908,Yoren,Night's Watch,299.0,2.0,19.0,13.0,1,0,1,1,0,0,0
909,Young Henly,Night's Watch,299.0,3.0,55.0,55.0,1,0,0,0,1,0,0
910,Ysilla,House Targaryen,NaN,NaN,NaN,8.0,1,0,0,0,0,0,1
911,Zei,Stark,NaN,NaN,NaN,64.0,0,0,0,0,1,0,0
912,Zollo,None,NaN,NaN,NaN,21.0,1,0,0,0,1,0,0
913,Yurkhaz zo Yunzak,None,300.0,5.0,59.0,47.0,1,0,0,0,0,0,1
914,Yezzan Zo Qaggaz,None,300.0,5.0,57.0,25.0,1,1,0,0,0,0,1
915,Torwynd the Tame,Wildling,300.0,5.0,73.0,73.0,1,0,0,0,1,0,0
916,Talbert Serry,Tyrell,300.0,4.0,29.0,29.0,1,1,0,0,0,1,0

In [12]:
df3 = pd.read_csv(('./input/character-predictions.csv'), encoding = 'ISO-8859-1')
df3

,S.No,actual,pred,alive,plod,name,title,male,culture,dateOfBirth,...,isAliveHeir,isAliveSpouse,isMarried,isNoble,age,numDeadRelations,boolDeadRelations,isPopular,popularity,isAlive
0,1,0,0,0.054,0.946,Viserys II Targaryen,NaN,1,NaN,NaN,...,0.0,NaN,0,0,NaN,11,1,1,0.605351,0
1,2,1,0,0.387,0.613,Walder Frey,Lord of the Crossing,1,Rivermen,208.0,...,NaN,1.0,1,1,97.0,1,1,1,0.896321,1
2,3,1,0,0.493,0.507,Addison Hill,Ser,1,NaN,NaN,...,NaN,NaN,0,1,NaN,0,0,0,0.267559,1
3,4,0,0,0.076,0.924,Aemma Arryn,Queen,0,NaN,82.0,...,NaN,0.0,1,1,23.0,0,0,0,0.183946,0
4,5,1,1,0.617,0.383,Sylva Santagar,Greenstone,0,Dornish,276.0,...,NaN,1.0,1,1,29.0,0,0,0,0.043478,1
5,6,1,0,0.021,0.979,Tommen Baratheon,NaN,1,NaN,NaN,...,1.0,NaN,0,0,NaN,5,1,1,1.000000,1
6,7,0,0,0.014,0.986,Valarr Targaryen,Hand of the King,1,Valyrian,183.0,...,NaN,1.0,1,1,26.0,0,0,1,0.431438,0
7,8,0,0,0.036,0.964,Viserys I Targaryen,NaN,1,NaN,NaN,...,1.0,NaN,0,0,NaN,5,1,1,0.678930,0
8,9,0,1,0.724,0.276,Wilbert,Ser,1,NaN,NaN,...,NaN,NaN,0,1,NaN,0,0,0,0.006689,0
9,10,1,0,0.391,0.609,Wilbert Osgrey,Ser,1,NaN,NaN,...,NaN,NaN,0,1,NaN,0,0,0,0.020067,1
10,11,0,0,0.167,0.833,Will,NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.163880,0
11,12,1,1,0.985,0.015,Will (orphan),NaN,0,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.003344,1
12,13,1,1,0.813,0.187,Will (squire),NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.003344,1
13,14,1,1,0.747,0.253,Will (Standfast),NaN,0,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.003344,1
14,15,1,1,0.705,0.295,Will (Treb),NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.003344,1
15,16,1,1,0.996,0.004,Will Humble,NaN,1,Ironborn,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.013378,1
16,17,1,1,0.984,0.016,Willam,NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.013378,1
17,18,1,1,0.604,0.396,Willem Wylde,Ser,1,NaN,NaN,...,NaN,NaN,0,1,NaN,0,0,0,0.020067,1
18,19,1,1,0.998,0.002,Willifer,Archmaester,0,NaN,NaN,...,NaN,NaN,0,1,NaN,0,0,0,0.006689,1
19,20,1,1,0.922,0.078,Willit,NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.010033,1
20,21,1,1,0.974,0.026,Willis Wode,Ser,1,NaN,NaN,...,NaN,NaN,0,1,NaN,0,0,0,0.020067,1
21,22,1,0,0.022,0.978,Willis Fell,Ser,0,NaN,NaN,...,NaN,NaN,0,1,NaN,0,0,0,0.023411,1
22,23,1,1,0.768,0.232,Willow Heddle,NaN,0,NaN,289.0,...,NaN,NaN,0,0,16.0,0,0,0,0.033445,1
23,24,1,1,0.561,0.439,Willum,Ser,1,NaN,NaN,...,NaN,NaN,0,1,NaN,0,0,0,0.000000,1
24,25,1,1,0.936,0.064,Wolmer,NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.003344,1
25,26,0,0,0.217,0.783,Willow Witch-eye,NaN,0,Free Folk,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.050167,0
26,27,0,0,0.193,0.807,Woth,NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.030100,0
27,28,1,1,0.710,0.290,Wulfe,NaN,1,Ironborn,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.023411,1
28,29,1,1,0.809,0.191,Wyl the Whittler,NaN,0,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.006689,1
29,30,0,0,0.203,0.797,Wyl (guard),NaN,0,Northmen,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.026756,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1916,1917,1,1,0.530,0.470,Tygett Lannister,Ser,1,NaN,250.0,...,NaN,1.0,1,1,55.0,0,0,0,0.110368,1
1917,1918,1,1,0.759,0.241,Sarella Sand,NaN,0,Dornishmen,280.0,...,NaN,NaN,0,0,25.0,1,1,0,0.103679,1
1918,1919,0,0,0.001,0.999,Rhaegar Targaryen,Prince of Dragonstone,1,Valyrian,259.0,...,NaN,0.0,1,1,24.0,11,1,1,0.799331,0
1919,1920,0,0,0.035,0.965,Drogo,Khal,0,Dothraki,267.0,...,NaN,1.0,1,0,32.0,5,1,1,0.558528,0
1920,1921,1,0,0.138,0.862,Dunsen,NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.040134,1
1921,1922,0,0,0.115,0.885,Barra,NaN,1,NaN,298.0,...,NaN,NaN,0,0,1.0,1,1,0,0.107023,0
1922,1923,1,1,0.985,0.015,Bethany Bolton,the Dreadfort,1,Northmen,NaN,...,NaN,1.0,1,1,NaN,0,0,0,0.043478,1
1923,1924,1,1,0.570,0.430,Desmond Grell,Ser,0,NaN,237.0,...,NaN,NaN,0,1,68.0,0,0,0,0.076923,1
1924,1925,1,0,0.353,0.647,Devan Seaworth,NaN,1,NaN,287.0,...,NaN,NaN,0,0,18.0,0,0,0,0.093645,1
1925,1926,1,0,0.226,0.774,Gendry,Ser,1,NaN,284.0,...,NaN,NaN,0,1,21.0,2,1,1,0.438127,1
1926,1927,1,1,0.964,0.036,Gran Goodbrother,NaN,1,Ironborn,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.026756,1
1927,1928,1,0,0.468,0.532,Loras Tyrell,Ser,1,The Reach,282.0,...,NaN,NaN,0,1,23.0,2,1,1,0.665552,1
1928,1929,1,1,0.918,0.082,Ricasso,Sunspear,0,NaN,NaN,...,NaN,NaN,0,1,NaN,0,0,0,0.070234,1
1929,1930,0,0,0.199,0.801,Stalwart Shield,NaN,0,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.043478,0
1930,1931,1,0,0.146,0.854,Yohn Royce,Runestone,1,Valemen,NaN,...,NaN,NaN,0,1,NaN,2,1,0,0.170569,1
1931,1932,1,0,0.284,0.716,Yandry,NaN,1,NaN,NaN,...,NaN,1.0,1,0,NaN,0,0,0,0.050167,1
1932,1933,1,1,0.913,0.087,Tarle,NaN,1,Ironborn,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.026756,1
1933,1934,1,1,0.767,0.233,Temmo,Khal,1,Dothraki,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.020067,1
1934,1935,0,0,0.001,0.999,Rohanne Webber,Coldmoat,0,NaN,185.0,...,NaN,1.0,1,1,100.0,0,0,0,0.170569,0
1935,1936,1,1,0.930,0.070,Gormond Goodbrother,NaN,1,Ironborn,282.0,...,NaN,NaN,0,0,23.0,0,0,0,0.040134,1
1936,1937,1,1,0.847,0.153,Walder Rivers,Ser,1,Rivermen,NaN,...,NaN,1.0,1,1,NaN,0,0,0,0.080268,1
1937,1938,0,0,0.155,0.845,Symon Silver Tongue,NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.046823,0
1938,1939,1,0,0.201,0.799,Moqorro,Slave of R'hllor,1,NaN,NaN,...,NaN,NaN,0,1,NaN,0,0,0,0.123746,1
1939,1940,1,1,0.982,0.018,Meg,NaN,0,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.010033,1
1940,1941,0,0,0.003,0.997,Laena Velaryon,NaN,0,Valyrian,93.0,...,NaN,0.0,1,0,27.0,0,0,0,0.140468,0
1941,1942,0,1,0.803,0.197,Luwin,NaN,1,Westeros,NaN,...,NaN,NaN,0,0,NaN,0,0,1,0.351171,0
1942,1943,0,1,0.987,0.013,Reek,NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.096990,0
1943,1944,1,1,0.520,0.480,Symeon Star-Eyes,NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.030100,1
1944,1945,1,1,0.637,0.363,Coldhands,NaN,1,NaN,NaN,...,NaN,NaN,0,0,NaN,0,0,0,0.130435,1
1945,1946,0,0,0.093,0.907,Tytos Lannister,Casterly Rock,1,NaN,220.0,...,NaN,1.0,1,1,47.0,4,1,0,0.210702,0